# Generated by Django 5.1.4 on 2025-01-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(blank=True, max_length=150, unique=True)),
                ('email', models.CharField(blank=True, max_length=150, unique=True)),
                ('birthdate', models.DateField()),
                ('sex', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=30)),
                ('profil', models.ImageField(blank=True, upload_to='profiles/')),
                ('origins', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('biography', models.TextField(max_length=500)),
                ('password', models.CharField(max_length=128)),
                ('students', models.PositiveIntegerField(default=0)),
                ('teachers', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
