# Generated by Django 5.1.4 on 2025-01-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_managers_users_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
