# Generated by Django 5.1.4 on 2025-01-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='courses/thumbnails/'),
        ),
    ]
